name: Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test database
      run: |
        python -c "
        import sys
        import os
        sys.path.append(os.path.abspath('.'))
        from customer_management.database.settings import engine
        
        with engine.connect() as conn:
            result = conn.execute('SELECT COUNT(*) FROM customers').scalar()
            print(f'Registros encontrados: {result}')
            assert result >= 5, 'Database should have at least 5 initial records'
        "
    
    - name: Test app
      run: |
        streamlit run app.py &
        sleep 5
        curl -s http://localhost:8501 > /dev/null

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy message
      run: echo "Pronto para deploy no Streamlit Cloud"
    